: [DTMF-additional-support] - add option description and example for transportType
versatica/jssip.net pull request #5
Opened 2020-05-11 16:18 UTC by acharlop

[DTMF-additional-support](https://idtjira.atlassian.net/browse/DTMF-additional-support)

2020-05-11 16:21 UTC, jmillan commented
inband DTMFs are not supported in JsSIP

2020-05-11 16:22 UTC, acharlop commented
just made a PR with support

2020-05-11 16:22 UTC, acharlop commented
https://github.com/versatica/JsSIP/pull/629

2020-05-12 14:06 UTC, ibc requested changes

2020-05-12 14:06 UTC, ibc commented on content/documentation/3.4.x/api/session.html
> +  "transportType" => "Optional @String@ INFO or RFC2833. Default value is @INFO@",
```suggestion
  "transportType" => "Optional @String@ 'INFO' or 'RFC2833'. Default value is 'INFO'",
```

2020-05-13 12:49 UTC, ibc approved these changes

2020-05-13 12:51 UTC, merged